# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import datetime
now=datetime.datetime.now()
class Migration(migrations.Migration):

    dependencies = [
        ('workplan', '0004_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=now),
            preserve_default=False,
        ),
    ]
